### ISSUE TITLE
Upgrading Airflow minor versions

### ISSUE THREAD

**Issue by cjk** [soggycactus/airflow-repo-template#12]
Hi @soggycactus ,
thanks for providing this useful template!

One question: I'm just starting off and noticed Airflow 2.0.1 is already out - should I simply adjust `AIRFLOW_VERSION` in the Makefile to use it or are there other prerequisites to take care of? 

Thanks!

**Comment by soggycactus** [comment]
Adjusting `AIRFLOW_VERSION` should be all that's required, since we are building our own Docker image and virtual environment - let me know if it works for you!

**Comment by cjk** [comment]
Trying to build with version 2.0.1 of Airflow currently results in an error (see below). However, it's hard to tell if this is related to v2.0.1 - could also be it's one of the two extras I'm including: `elasticsearch` and `docker`.

```
[...]
Step 9/9 : RUN make internal-install-deps
 ---> Using cache
 ---> 2adf3fc23b65
Successfully built 2adf3fc23b65
Successfully tagged airflow-repo-template_scheduler:latest
WARNING: Image for service scheduler was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
airflow-repo-template_postgres_1 is up-to-date
Starting airflow-repo-template_initdb_1 ... done
Creating airflow-repo-template_webserver_1 ... done
Creating airflow-repo-template_scheduler_1 ... done
Attaching to airflow-repo-template_webserver_1, airflow-repo-template_scheduler_1
scheduler_1  | [2021-03-26 09:43:06,033] {cli_action_loggers.py:105} WARNING - Failed to log action with (psycopg2.OperationalError) could not translate host name "host.docker.internal" to address: Name or service not known
scheduler_1  | 
scheduler_1  | (Background on this error at: http://sqlalche.me/e/13/e3q8)
scheduler_1  |   ____________       _____________
scheduler_1  |  ____    |__( )_________  __/__  /________      __
scheduler_1  | ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
scheduler_1  | ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
scheduler_1  |  _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
scheduler_1  |     return fn()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
scheduler_1  |     return _ConnectionFairy._checkout(self)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
scheduler_1  |     fairy = _ConnectionRecord.checkout(pool)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
scheduler_1  |     rec = pool._do_get()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
[...]
```

**Comment by cjk** [comment]
Update: Even Airflow 2.0.0 doesn't build correctly and fails with `psycopg2.OperationalError: could not translate host name "host.docker.internal" to address: Name or service not known` somewhere in SQLAlchemy in the Scheduler-service.

Not sure what may cause this, similar issues on SO seem to point in the docker-compose file direction:
> `AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@host.docker.internal:5439/airflow`

and:
> If you want to access host database then you can pass HOST IP or you can use host.docker.internal but this does not work in linux, for mac and window it should work.

... and of course I'm on Linux `x86_64 GNU/Linux` :cry:

**Comment by cjk** [comment]
OK, I resolved the issue above following the advice in [this comment](https://github.com/docker/for-linux/issues/264#issuecomment-763555307) that addresses the resolve-host problem for Linux.

In hindsight this issues has nothing to do with Airflow and version-compatibility of this template-repo (should have made it separate). But I hope it helps fellow Linux-users that stumble upon this.

Also, the above workaround may not be the best way to tackle this, just couldn't figure out a better way for now.

**Comment by soggycactus** [comment]
Hey @cjk thanks for finding this! I fixed this issue in #13 - the root cause was that the docker-compose file was using a keyword that only works on Mac OS - I switched the Postgres connection string to use docker-compose's internal DNS, which should be OS agnostic

Let me know if this fixes, and if you encounter any other problems feel free to reopen the issue

**Comment by cjk** [comment]
Thanks, this indeed fixes the problem, so Airflow now starts without issues.

However, I noticed that on shutdown (using `make stop-airflow`) it's running into an error that looks related:

```
[...]
scheduler_1  | [2021-03-29 17:30:45,174] {scheduler_job.py:746} INFO - Exiting gracefully upon receiving signal 15
scheduler_1  | [2021-03-29 17:30:46,179] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 143
scheduler_1  | [2021-03-29 17:30:46,232] {process_utils.py:66} INFO - Process psutil.Process(pid=143, status='terminated', exitcode=0, started='17:30:30') (143) terminated with exit code 0
scheduler_1  | [2021-03-29 17:30:46,236] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 143
scheduler_1  | [2021-03-29 17:30:46,236] {scheduler_job.py:1301} INFO - Exited execute loop
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 817, in _checkout
scheduler_1  |     raise exc.InvalidatePoolError()
scheduler_1  | sqlalchemy.exc.InvalidatePoolError: ()
scheduler_1  | 
scheduler_1  | During handling of the above exception, another exception occurred:
scheduler_1  | 
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
scheduler_1  |     return fn()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
scheduler_1  |     return _ConnectionFairy._checkout(self)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 847, in _checkout
scheduler_1  |     fairy._connection_record._checkin_failed(err)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
scheduler_1  |     compat.raise_(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
scheduler_1  |     raise exception
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 843, in _checkout
scheduler_1  |     fairy._connection_record.get_connection()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 610, in get_connection
scheduler_1  |     self.__connect()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
scheduler_1  |     pool.logger.debug("Error on connect(): %s", e)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
scheduler_1  |     compat.raise_(
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
scheduler_1  |     raise exception
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
scheduler_1  |     connection = pool._invoke_creator(self)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
scheduler_1  |     return dialect.connect(*cargs, **cparams)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
scheduler_1  |     return self.dbapi.connect(*cargs, **cparams)
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
scheduler_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
scheduler_1  | psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known
[...]
```

Hope it's re-producible on your side!

**Comment by soggycactus** [comment]
> Thanks, this indeed fixes the problem, so Airflow now starts without issues.
> 
> However, I noticed that on shutdown (using `make stop-airflow`) it's running into an error that looks related:
> 
> ```
> [...]
> scheduler_1  | [2021-03-29 17:30:45,174] {scheduler_job.py:746} INFO - Exiting gracefully upon receiving signal 15
> scheduler_1  | [2021-03-29 17:30:46,179] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 143
> scheduler_1  | [2021-03-29 17:30:46,232] {process_utils.py:66} INFO - Process psutil.Process(pid=143, status='terminated', exitcode=0, started='17:30:30') (143) terminated with exit code 0
> scheduler_1  | [2021-03-29 17:30:46,236] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 143
> scheduler_1  | [2021-03-29 17:30:46,236] {scheduler_job.py:1301} INFO - Exited execute loop
> scheduler_1  | Traceback (most recent call last):
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 817, in _checkout
> scheduler_1  |     raise exc.InvalidatePoolError()
> scheduler_1  | sqlalchemy.exc.InvalidatePoolError: ()
> scheduler_1  | 
> scheduler_1  | During handling of the above exception, another exception occurred:
> scheduler_1  | 
> scheduler_1  | Traceback (most recent call last):
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
> scheduler_1  |     return fn()
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
> scheduler_1  |     return _ConnectionFairy._checkout(self)
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 847, in _checkout
> scheduler_1  |     fairy._connection_record._checkin_failed(err)
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
> scheduler_1  |     compat.raise_(
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
> scheduler_1  |     raise exception
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 843, in _checkout
> scheduler_1  |     fairy._connection_record.get_connection()
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 610, in get_connection
> scheduler_1  |     self.__connect()
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
> scheduler_1  |     pool.logger.debug("Error on connect(): %s", e)
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
> scheduler_1  |     compat.raise_(
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
> scheduler_1  |     raise exception
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
> scheduler_1  |     connection = pool._invoke_creator(self)
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
> scheduler_1  |     return dialect.connect(*cargs, **cparams)
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
> scheduler_1  |     return self.dbapi.connect(*cargs, **cparams)
> scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
> scheduler_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> scheduler_1  | psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known
> [...]
> ```
> 
> Hope it's re-producible on your side!

This is expected behavior, `make stop-airflow` is just an alias for `docker-compose down`, which stops all containers - what you're seeing is just the logs as the containers shut down, you should still see every container exit with code 0, indicating that they shut down gracefully.

**Comment by cjk** [comment]
I see, then all seems to be fine. Thanks for checking!
