### ISSUE TITLE
Run airflow not form `root`

### ISSUE THREAD

**Issue by toplenboren** [soggycactus/airflow-repo-template#16]
**Hello!**

Thank you for this template.

--

I try to run airflow not from the `root` user:

For this I change the dockerfile:

From
```
# Install Airflow and any additonal dependencies
WORKDIR /root
```

To
```
# Install Airflow and any additonal dependencies
WORKDIR /app
```

And then create user `airflow` and give him all the rights to the `/app` directory

After that I change all occurencies of `/root` in `docker-compose` file, so the volumes point to the `/app` dir now

--

I expect that when I boot up airflow I'd get my DAGs up and running, but instead it seems like DAGs have not been imported at all 

Could you please point me in a way why this might happen? I did not find a way to specify DAGs loading folder in the code :(

**Comment by soggycactus** [comment]
Did you change the `AIRFLOW_HOME` environment variable here: https://github.com/soggycactus/airflow-repo-template/blob/master/docker-compose.yaml#L20

**Comment by toplenboren** [comment]
> Did you change the `AIRFLOW_HOME` environment variable here: https://github.com/soggycactus/airflow-repo-template/blob/master/docker-compose.yaml#L20

Yep, changed all occurrences from `/root` to `/app` in `docker-compose`

Thought it might be handy to see `Dockerfile` -- here it is:

```Dockerfile
FROM python:3.8-slim-buster


RUN apt update
# Install Airflow pre-requisites: https://airflow.apache.org/docs/apache-airflow/2.0.0/installation.html#getting-airflow
RUN apt install build-essential -y
# Install Airflow system dependencies: https://airflow.apache.org/docs/apache-airflow/stable/installation.html#system-dependencies
# NOTE: we have changed krb5-user to libkrb5-dev for a non-interactive installation
RUN apt-get install -y --no-install-recommends \
    freetds-bin \
    ldap-utils \
    libffi6 \
    libkrb5-dev \
    libsasl2-2 \
    libsasl2-modules \
    libssl1.1 \
    locales  \
    lsb-release \
    sasl2-bin \
    sqlite3 \
    unixodbc

# Install Airflow and any additonal dependencies
WORKDIR /app

COPY Makefile /app/Makefile
COPY airflow.requirements.txt /app/airflow.requirements.txt

RUN make internal-install-airflow
RUN make internal-install-deps

RUN useradd -u 8877 -m airflow
RUN chmod -R 777 /app

USER airflow
```

When building a container, and then running `make start-airflow` i get a following error:

```
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/usr/local/bin/airflow", line 5, in <module>
scheduler_1  |     from airflow.__main__ import main
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/airflow/__init__.py", line 34, in <module>
scheduler_1  |     from airflow import settings
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/airflow/settings.py", line 34, in <module>
scheduler_1  |     from airflow.configuration import AIRFLOW_HOME, WEBSERVER_CONFIG, conf  # NOQA F401
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/airflow/configuration.py", line 1111, in <module>
scheduler_1  |     conf = initialize_config()
scheduler_1  |   File "/usr/local/lib/python3.8/site-packages/airflow/configuration.py", line 835, in initialize_config
scheduler_1  |     with open(AIRFLOW_CONFIG, 'w') as file:
scheduler_1  | PermissionError: [Errno 13] Permission denied: '/app/airflow/airflow.cfg'
airflow_scheduler_1 exited with code 1
```

I also tried adding this line to `Dockerfile`

`COPY airflow.cfg /app/airflow/airflow.cfg`

But i produced another error :(

**Comment by soggycactus** [comment]
This seems to just be an issue with they way you're attempting to change permissions, and not anything wrong with this template repository. You likely need to use `chown` to have the `airflow` user be the new owner of the `app` directory.
